package com.bank.domain.entities;

public enum SystemRole {
    NATURAL_PERSON_CLIENT,
    BUSINESS_CLIENT,
    TELLER_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    COMPANY_EMPLOYEE,
    COMPANY_SUPERVISOR,
    INTERNAL_ANALYST
}
