server:
  port: 8080

spring:
  application:
    name: bank-api
  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb

# Configuración OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true

bank:
  bitacora:
    storage: memory
  security:
    # Formato: usuario:idCliente,usuario2:idCliente2
    user-client-map: cliente_natural:cliente_natural_id,cliente_empresa:cliente_empresa_id,empleado_empresa:empresa_demo_id,supervisor:empresa_demo_id
  transfer:
    approval-threshold: 10000
    approval-expiration-minutes: 60
